#--------------------web-server-------------------------

server:
  port: 80


#----------------------spring---------------------------
spring:
  data:
    mongodb:
      #host: localhost
      #port: 27017
      host: ds052408.mlab.com
      port: 52408
      database: smart-hotel
      username: vking34
      password: vking34

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

#----------------------security--------------------------
security:
  jwt:
    expiry-in-milliseconds: 86400000  # 1 day
    secret-key: vking34

#----------------------pusher----------------------------
pusher:
  id: 737748
  key: 69053ddd28185a9726aa
  secret: 4e988776643fcce1a466
  cluster: ap1
  encrypted: true